### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [hardelean/prj-rev-bwfs-dasmoto#1]
Good job splitting your html in sections with divs. I would add unique attributes to the divs so you can differentiate between the different sections. Might be worth moving the id from the h2 in to the div instead.

https://github.com/hardelean/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L9-L16

**Comment by hardelean** [comment]
Updated index.html to include this issue.
