### ISSUE TITLE
use alt attribute on image tags

### ISSUE THREAD

**Issue by rimmesbe** [hardelean/prj-rev-bwfs-dasmoto#2]
Try to get in the habit of describing your images with the alt attribute. This description will show up incase the image doesn't load, it will be read by screen readers, and it makes your code looks more professional.
https://github.com/hardelean/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/index.html#L11

https://www.codecademy.com/articles/accessibility

**Comment by hardelean** [comment]
Updated index.html to include this issue.
