### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [hardelean/prj-rev-bwfs-dasmoto#3]
The global selector works, but it's not the best practice. Global selectors have a slow processing speed and are hard to overwrite in certain cases. A better option is to use inheritance:
html { font-family: Helvetica; }
Now all elements will inherit this font as default.

https://github.com/hardelean/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/resources/style.css#L1-L3

**Comment by hardelean** [comment]
Updated style.css to include this issue.
