### ISSUE TITLE
keep CSS DRY

### ISSUE THREAD

**Issue by rimmesbe** [hardelean/prj-rev-bwfs-dasmoto#5]
DRY (Don't Repeat Yourself) is a common phrase used in programming. It basically means don't repeat code you've already created. In this case you are re-writing many of the same styling for all the h2 elements. Instead you should extract these shared stylings into one selector. You can do this by creating a new class for the elements to share or use some other selector that targets all of them.
h2 { }

https://github.com/hardelean/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts/resources/style.css#L18-L20

**Comment by hardelean** [comment]
Updated index.html to include this issue.
