### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [hardelean/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques here and kept your code well organized. Take a look at the issues I created as they will help optimize your code and best practice. Here is a good article with some tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by hardelean** [comment]
Thank you very much Ryan!
Fantastic feedback! I thought there are not so many posibile improvements
to such an easy website.
I am more than honored to get all these improvement feedback. Actually I am
already implementing all of them.
This is the very best course I have ever taken online!

All the best!
Horia Ardelean
